name: Deploy Docker Compose to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Stop the server
        run: ssh prod 'cd ${{ secrets.REPO_PATH }} && docker-compose down'

      - name: fetch and reset
        run: ssh prod 'cd ${{ secrets.REPO_PATH }} && git fetch && git reset --hard origin/main'

      - name: Start the server
        run: ssh prod 'cd ${{ secrets.REPO_PATH }} && docker-compose up -d'
