name: Deploy Docker Compose to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ssh
        
    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Add GitHub to known hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      
    - name: Add private key to agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add <(echo ${{ secrets.SSH_PRIVATE_KEY }})

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.REPO_PATH }} && git pull && docker-compose down && docker-compose up -d'
