name: Deploy Docker Compose to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: alpine-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy with Docker Compose
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no -p ${SSH_PORT} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /path/to/project && git pull && docker-compose up -d'
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
