name: Deploy Docker Compose to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ssh
        
    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Add GitHub to known hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      
    - name: Add private key to agent
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
        chmod 600 /home/runner/.sssh/id_ed25519

#    - name: Deploy with Docker Compose
#      run: |
#        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.REPO_PATH }} && git pull && docker-compose down && docker-compose up -d'
    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -v -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'touch hello_world'
